import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "../app/providers";
import Navbar from "@/components/Navbar";
import Backdrop from "@/components/Backdrop";
import { AppProvider } from "@/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <AppProvider>
          <Providers>
            <div className="flex min-h-screen flex-col items-center">
              <Navbar />
              <main className="py-12 w-11/12 z-0">{children}</main>
              <Backdrop />
            </div>
          </Providers>
        </AppProvider>
      </body>
    </html>
  );
}
